Repository sweng-group-20/cryptocurrency-centralisation-visualisation, pull requests merged in 2021-04, with the labels that each got.

#36 Add basic unit tests
  server/.eslintrc.js
  server/package.json
  server/tests/routes/bitcoin.test.js
  server/tests/routes/ethereum.test.js
  server/yarn.lock
Labels: enhancement

#37 The gratitude branch
  client/package.json
  client/src/components/Bitcoin.jsx
  client/src/components/CryptocurrencyData.jsx
  client/src/components/Ethereum.jsx
  client/src/components/layers/Application.jsx
  client/src/components/layers/Consensus.jsx
  client/src/components/layers/Governance.jsx
  client/src/components/layers/Incentive.jsx
  client/src/components/layers/Network.jsx
  client/src/components/layers/Operational.jsx
  client/yarn.lock
  server/src/routes/bitcoin/application.js
  server/src/routes/bitcoin/consensus.js
  server/src/routes/bitcoin/governance.js
  server/src/routes/bitcoin/incentive.js
  server/src/routes/bitcoin/network.js
  server/src/routes/bitcoin/operational.js
  server/src/routes/ethereum/application.js
  server/src/routes/ethereum/consensus.js
  server/src/routes/ethereum/governance.js
  server/src/routes/ethereum/incentive.js
  server/src/routes/ethereum/network.js
  server/src/routes/ethereum/operational.js
Labels: documentation

#38 Fix concurrency bug, fix database init script
  client/docker/dev.ps1
  client/docker/dev.sh
  docker/dev.ps1
  docker/dev.sh
  server/docker/dev.ps1
  server/docker/dev.sh
  server/sql_scripts/dump_db.sh
  server/src/app.js
  server/src/graph_data/satoshi_index.js
  server/src/routes/index.js
Labels: bug

#39 Added testing for response body structure for the endpoints
  server/tests/routes/bitcoin.test.js
  server/tests/routes/ethereum.test.js
Labels: infrastructure

#41 Update docker scripts
  .env_example
  README.md
  client/Dockerfile
  client/docker/dev.ps1
  client/docker/dev.sh
  client/docker/docker-compose.dev.yml
  client/docker/docker-compose.yml
  client/docker/start.ps1
  client/docker/start.sh
  client/docker/stop.ps1
  client/docker/stop.sh
  client/nginx.conf
  client/package.json
  client/src/components/Bitcoin.jsx
  client/src/components/Ethereum.jsx
  database/.gitignore
  database/Dockerfile
  database/dump_db.sh
  database/init.sql
  docker/dev.ps1
  docker/dev.sh
  docker/docker-compose.dev.yml
  docker/docker-compose.prod.yml
  docker/docker-compose.yml
  docker/start.ps1
  docker/start.sh
  docker/stop.ps1
  server/.gitignore
  server/docker/dev.ps1
  server/docker/dev.sh
  server/docker/docker-compose.dev.yml
  server/docker/docker-compose.yml
  server/docker/start.ps1
  server/docker/start.sh
  server/docker/stop.ps1
  server/docker/stop.sh
  server/package.json
  server/sql_scripts/dump_db.sh
  server/src/app.js
  server/src/graph_data/github_comments.js
Labels: infrastructure

#44 New choropleth graph, fix bugs
  client/.eslintrc.js
  client/package.json
  client/src/components/graphs/GeoMap.css
  client/src/components/graphs/GeoMap.jsx
  client/src/components/graphs/LineGraph.jsx
  client/src/components/graphs/entities/Legend.jsx
  client/src/components/graphs/entities/LegendItem.js
  client/src/components/graphs/entities/LegendItems.js
  client/src/components/graphs/entities/SetCountries.js
  client/src/components/graphs/world_countries.json
  client/src/components/layers/Application.jsx
  client/src/components/layers/Consensus.jsx
  client/src/components/layers/DataSource.css
  client/src/components/layers/DataSource.jsx
  client/src/components/layers/Governance.css
  client/src/components/layers/Governance.jsx
  client/src/components/layers/Incentive.jsx
  client/src/components/layers/Network.css
  client/src/components/layers/Network.jsx
  client/src/components/layers/Operational.jsx
  client/yarn.lock
  docker/db.dump
  server/package.json
  server/src/routes/bitcoin/governance.js
  server/src/routes/ethereum/governance.js
Labels: documentation, enhancement

#45 Remove db.dump
  docker/db.dump
Labels: bug

#46 Update README.md
  .env_example
  .github/images/api-docs.gif
  .github/images/dashboard.gif
  README.md
  client/package.json
  client/yarn.lock
  server/package.json
  server/yarn.lock
Labels: documentation

#47 Added bibliography to README.md
  README.md
Labels: documentation

#49 Update README.md
  README.md
Labels: documentation
