Repository sweng-group-20/cryptocurrency-centralisation-visualisation, pull requests merged in 2021-03, with the labels that each got.

#3 Fix codeowners file
  .github/CODEOWNERS
Labels: bug

#5 Update
  README.md
Labels: documentation

#20 Add Stephen to authors in README.md
  README.md
Labels: documentation

#23 Modified operational layer middleware for bitcoin and ethereum
  server/src/app.js
  server/src/routes/bitcoin/operational.js
  server/src/routes/ethereum/operational.js
Labels: enhancement

#25 Add application layer endpoints
  .env_example
  README.md
  client/.eslintrc.js
  docker/docker-compose.dev.yml
  docker/docker-compose.yml
  server/.eslintrc.js
  server/.gitignore
  server/docker/docker-compose.dev.yml
  server/docker/docker-compose.yml
  server/package.json
  server/sql_scripts/init.sql
  server/src/app.js
  server/src/db/index.js
  server/src/errors/GitHubError.js
  server/src/errors/GraphQLError.js
  server/src/graph_data/github_comments.js
  server/src/graph_data/satoshi_index.js
  server/src/http_clients/base.js
  server/src/http_clients/github.js
  server/src/logger/index.js
  server/src/routes/api_docs.js
  server/src/routes/bitcoin/application.js
  server/src/routes/bitcoin/operational.js
  server/src/routes/ethereum/application.js
  server/src/routes/ethereum/index.js
  server/src/routes/ethereum/operational.js
  server/yarn.lock
Labels: enhancement

#27 Merging backend into main to link with frontend
  README.md
  client/package.json
  client/src/App.jsx
  client/src/components/GeoMap.jsx
  client/src/components/PieChart.jsx
  client/src/components/ResponsiveLineCanvas.jsx
  client/src/components/world_countries.json
  client/src/pages/GraphPage.jsx
  client/yarn.lock
  server/.prettierrc.js
  server/package.json
  server/src/routes/bitcoin/consensus.js
  server/src/routes/bitcoin/index.js
  server/src/routes/bitcoin/network.js
  server/src/routes/ethereum/CountryCodes.json
  server/src/routes/ethereum/consensus.js
  server/src/routes/ethereum/index.js
  server/src/routes/ethereum/network.js
  server/yarn.lock
Labels: enhancement
